name: emosdk_launcher
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.5.1
  ps_list: ^0.0.5


  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  video_player_win: ^3.2.0
  ffmpeg_kit_flutter_minimal: ^6.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/echo_games_lab/
    - assets/echo_games_lab/images/
    - assets/echo_games_lab/videos/
    - assets/emosdk/
    - assets/emosdk/images/
    - assets/emosdk/videos/
    - assets/exceedium_games/
    - assets/exceedium_games/images/
    - assets/exceedium_games/videos/
    - assets/flesh_insane_team/
    - assets/flesh_insane_team/images/
    - assets/flesh_insane_team/videos/
    - assets/iz_hazard/
    - assets/iz_hazard/images/
    - assets/iz_hazard/videos/
    - assets/sigil_games/
    - assets/sigil_games/images/
    - assets/sigil_games/videos/
    - assets/visual_floss/
    - assets/visual_floss/images/
    - assets/visual_floss/videos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
